# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ncsd.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gbParameters = QtWidgets.QGroupBox(self.centralwidget)
        self.gbParameters.setTitle("")
        self.gbParameters.setObjectName("gbParameters")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbParameters)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.gbParameters)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lbDirectoryName = QtWidgets.QLabel(self.gbParameters)
        self.lbDirectoryName.setText("")
        self.lbDirectoryName.setObjectName("lbDirectoryName")
        self.horizontalLayout_5.addWidget(self.lbDirectoryName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.gbParameters)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lbFileName = QtWidgets.QLabel(self.gbParameters)
        self.lbFileName.setText("")
        self.lbFileName.setObjectName("lbFileName")
        self.horizontalLayout.addWidget(self.lbFileName)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.gbParameters)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.sbAngle = QtWidgets.QSpinBox(self.gbParameters)
        self.sbAngle.setMinimum(1)
        self.sbAngle.setMaximum(360)
        self.sbAngle.setSingleStep(10)
        self.sbAngle.setProperty("value", 20)
        self.sbAngle.setObjectName("sbAngle")
        self.horizontalLayout_2.addWidget(self.sbAngle)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.cbSVG = QtWidgets.QCheckBox(self.gbParameters)
        self.cbSVG.setObjectName("cbSVG")
        self.verticalLayout.addWidget(self.cbSVG)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.gbParameters)
        self.label_3.setEnabled(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.leOutputFile = QtWidgets.QLineEdit(self.gbParameters)
        self.leOutputFile.setEnabled(False)
        self.leOutputFile.setObjectName("leOutputFile")
        self.horizontalLayout_3.addWidget(self.leOutputFile)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.gbParameters)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pbMarkersAnalysis = QtWidgets.QPushButton(self.tab)
        self.pbMarkersAnalysis.setObjectName("pbMarkersAnalysis")
        self.verticalLayout_4.addWidget(self.pbMarkersAnalysis)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.le_centerContour_2 = QtWidgets.QLineEdit(self.tab_2)
        self.le_centerContour_2.setObjectName("le_centerContour_2")
        self.horizontalLayout_8.addWidget(self.le_centerContour_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.leRefContour_2 = QtWidgets.QLineEdit(self.tab_2)
        self.leRefContour_2.setObjectName("leRefContour_2")
        self.horizontalLayout_9.addWidget(self.leRefContour_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.pbCellBodiesAnalysis = QtWidgets.QPushButton(self.tab_2)
        self.pbCellBodiesAnalysis.setObjectName("pbCellBodiesAnalysis")
        self.verticalLayout_6.addWidget(self.pbCellBodiesAnalysis)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.le_centerContour = QtWidgets.QLineEdit(self.tab_3)
        self.le_centerContour.setObjectName("le_centerContour")
        self.horizontalLayout_7.addWidget(self.le_centerContour)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.leRefContour = QtWidgets.QLineEdit(self.tab_3)
        self.leRefContour.setObjectName("leRefContour")
        self.horizontalLayout_6.addWidget(self.leRefContour)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.sbSubContoursNb = QtWidgets.QSpinBox(self.tab_3)
        self.sbSubContoursNb.setMinimum(0)
        self.sbSubContoursNb.setMaximum(100)
        self.sbSubContoursNb.setSingleStep(1)
        self.sbSubContoursNb.setProperty("value", 10)
        self.sbSubContoursNb.setObjectName("sbSubContoursNb")
        self.horizontalLayout_4.addWidget(self.sbSubContoursNb)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pbDistanceAnalysis = QtWidgets.QPushButton(self.tab_3)
        self.pbDistanceAnalysis.setObjectName("pbDistanceAnalysis")
        self.verticalLayout_8.addWidget(self.pbDistanceAnalysis)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.pbDistanceAnalysis.raise_()
        self.label_7.raise_()
        self.le_centerContour.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOpen_Neurolucida_XML_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_Neurolucida_XML_file.setObjectName("actionOpen_Neurolucida_XML_file")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpenAll = QtWidgets.QAction(MainWindow)
        self.actionOpenAll.setObjectName("actionOpenAll")
        self.menu.addAction(self.actionOpen_Neurolucida_XML_file)
        self.menu.addAction(self.actionOpenAll)
        self.menu.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Neurolucida Companion for Spatial Distribution Analysis"))
        self.label_4.setText(_translate("MainWindow", "Directory name:"))
        self.label.setText(_translate("MainWindow", "Neurolucida XML file:"))
        self.label_2.setText(_translate("MainWindow", "Sector angle"))
        self.cbSVG.setText(_translate("MainWindow", "Produce SVG file"))
        self.label_3.setText(_translate("MainWindow", "Output file"))
        self.pbMarkersAnalysis.setText(_translate("MainWindow", "Markers analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Markers analysis"))
        self.label_8.setText(_translate("MainWindow", "Center contour"))
        self.label_9.setText(_translate("MainWindow", "Reference contour"))
        self.pbCellBodiesAnalysis.setText(_translate("MainWindow", "Cell bodies analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Cell bodies analysis"))
        self.label_7.setText(_translate("MainWindow", "Center contour"))
        self.label_6.setText(_translate("MainWindow", "Reference contour"))
        self.label_5.setText(_translate("MainWindow", "Number of subcontours"))
        self.pbDistanceAnalysis.setText(_translate("MainWindow", "Distance analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Distance analysis"))
        self.menu.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionOpen_Neurolucida_XML_file.setText(_translate("MainWindow", "Open Neurolucida XML file"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.actionOpenAll.setText(_translate("MainWindow", "Open all XML from directory"))

